-- phpMyAdmin SQL Dump
-- version 2.11.0-rc1
-- http://www.phpmyadmin.net
--
-- Generation Time: Oct 13, 2009 at 05:10 PM
-- Server version: 5.0.84
-- PHP Version: 5.2.3

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Database: `game_garbage`
--

-- --------------------------------------------------------

--
-- Table structure for table `images_buttons`
--

CREATE TABLE IF NOT EXISTS `images_buttons` (
  `rec_order` int(11) NOT NULL default '0',
  `image_name` varchar(100) NOT NULL default '' COMMENT 'Special cases: ''next'', %reset%, and ''show_form''',
  `file_name` varchar(100) NOT NULL default '',
  `display_order` int(11) NOT NULL default '1' COMMENT 'Sequence among buttons on this screen',
  `short_text` varchar(200) default NULL COMMENT 'Displayed on-screen',
  `rollover_text` mediumtext COMMENT 'Display upon button rollover',
  `pos_x` int(11) NOT NULL default '0',
  `pos_y` int(11) NOT NULL default '0',
  `go_to` int(11) NOT NULL default '999' COMMENT 'Corresponds to destination text_input screen',
  `tonnage_sorted` mediumint(9) NOT NULL default '0' COMMENT 'Phase 1',
  `tonnage_unsorted` mediumint(9) NOT NULL default '0' COMMENT 'Phase 1',
  `tonnage_diverted` float NOT NULL default '0' COMMENT 'Phase 1',
  `calculated_on_tonnage` enum('sorted','unsorted') default NULL,
  `miles_truck_dos` float NOT NULL default '0',
  `miles_truck_big` float NOT NULL default '0',
  `miles_rail` float NOT NULL default '0',
  `miles_barge` float NOT NULL default '0',
  `timestamp` timestamp NOT NULL default '0000-00-00 00:00:00' on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`rec_order`,`image_name`),
  KEY `display_order` (`display_order`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `images_buttons`
--

INSERT INTO `images_buttons` (`rec_order`, `image_name`, `file_name`, `display_order`, `short_text`, `rollover_text`, `pos_x`, `pos_y`, `go_to`, `tonnage_sorted`, `tonnage_unsorted`, `tonnage_diverted`, `calculated_on_tonnage`, `miles_truck_dos`, `miles_truck_big`, `miles_rail`, `miles_barge`, `timestamp`) VALUES
(10, 'next', 'next.png', 1, NULL, NULL, 0, 0, 12, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-07 21:54:16'),
(12, 'next', 'next.png', 1, NULL, NULL, 0, 0, 14, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-07 21:54:35'),
(14, 'next', 'next.png', 1, NULL, NULL, 0, 0, 24, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 17:06:54'),
(20, 'next', 'next.png', 1, NULL, NULL, 0, 0, 24, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-07 21:54:16'),
(24, 'next', 'next.png', 1, NULL, NULL, 0, 0, 30, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-07 21:54:16'),
(30, 'plastic_reduce', 'plastic_reduce.png', 1, 'Don''t Drink Bottled Water', 'Approximately 25 percent of all bottled water is municipal tap water. New York''s water is so pure - it originates in streams upstate - that it does not need to be filtered.  It costs 49 cents a year to use New York City tap water, while it costs $1,400 a year to purchase bottled water.', 0, 0, 90, 0, 0, 17677, NULL, 0, 0, 0, 0, '2007-11-14 11:07:39'),
(30, 'plastic_reuse', 'plastic_reuse.png', 2, 'Refill Use Again', 'In 2006, Americans bought 50 billion water bottles - 167 for every person in the country. About 38 billion of those bottles ended up in a landfill.', 0, 0, 60, 0, 0, 13258, NULL, 0, 0, 0, 0, '2007-11-14 11:07:39'),
(30, 'plastic_unsorted', 'plastic_unsorted.png', 2, 'Toss it in the Can', 'Nationwide, 2.5 million plastic bottles are thrown away every hour.', 0, 0, 99, 0, 17677, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:31:01'),
(30, 'plastic_sorted', 'paper_sorted.png', 1, 'Sort for Recycling', 'Nationwide, 25 percent of plastic bottles are recycled. Of all the glass, metal and plastics collected for recycling in the city, plastics make up about 13 percent. For residences, the city''s waste diversion rate for recycling is about 18 percent. The rate could be as a high as 36 percent, but 50 percent of materials that could be recycled are thrown out with the regular trash.', 0, 0, 97, 17677, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 16:10:01'),
(50, 'next', 'next.png', 1, '', NULL, 0, 0, 60, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(60, 'plastic_sorted', 'paper_sorted.png', 1, 'Sort for Recycling', 'Nationwide, 25 percent of plastic bottles are recycled. Of all the glass, metal and plastics collected for recycling in the city, plastics make up about 13 percent. For residences, the city''s waste diversion rate for recycling is about 18 percent. The rate could be as a high as 36 percent, but 50 percent of materials that could be recycled are thrown out with the regular trash.', 0, 0, 96, 4420, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:15:00'),
(60, 'plastic_unsorted', 'plastic_unsorted.png', 2, 'Toss it in the Can', 'Nationwide, 2.5 million plastic bottles are thrown away every hour.', 0, 0, 95, 0, 4420, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:31:01'),
(90, 'next', 'next.png', 1, '', NULL, 0, 0, 100, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(95, 'next', 'next.png', 1, '', NULL, 0, 0, 100, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(96, 'next', 'next.png', 1, '', NULL, 0, 0, 100, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 15:01:53'),
(97, 'next', 'next.png', 1, '', NULL, 0, 0, 100, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(99, 'next', 'next.png', 1, '', NULL, 0, 0, 100, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(100, 'towel_reuse', 'towel_reuse.png', 1, 'Reuse it as a Rag', 'This will keep it out of the landfill a while longer and save you the expense of buying sponges, paper towels and Swiffers.', 0, 0, 140, 0, 9278, 9278, NULL, 0, 0, 0, 0, '2007-11-12 11:44:25'),
(100, 'towel_unsorted', 'towel_unsorted.png', 2, 'Toss it in the Garbage', 'New Yorkers throw away 18,556 tons of towels, sheets and pillowcases and a total of about 190,000 tons of recyclable textiles a year.', 0, 0, 145, 0, 18556, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:31:01'),
(100, 'towel_divert', 'towel_divert.png', 3, 'Drop it off at Goodwill', 'One person''s garbage is another one''s gold. You may be sick of that chartreuse terry cloth but it could be just the thing for another New Yorker. Eventually, getting rid of it will be that person''s responsibility.', 0, 0, 140, 0, 9278, 9278, NULL, 0, 0, 0, 0, '2007-11-12 11:44:25'),
(140, 'next', 'next.png', 1, NULL, NULL, 0, 0, 150, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(145, 'next', 'next.png', 1, NULL, NULL, 0, 0, 150, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(150, 'compost_unsorted', 'compost_unsorted.png', 1, 'Toss it in the Can', 'Food waste accounts for about 22 percent of all residential garbage thrown away in NYC, with lawn clippings, dried leaves, branches and the like making up another 6 to 7.', 0, 0, 190, 0, 745000, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:32:01'),
(150, 'compost_sorted', 'compost_sorted.png', 2, 'Sort it for Curbside Pickup', 'The Department of Sanitation currently collects limited amounts of yard waste, fall leaves and Christmas trees. If New Yorkers went all out and composted food scraps and other compostables with our yard waste, up to 30 percent of the city''s refuse by some counts could avoid the landfill.', 0, 0, 192, 745000, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:44:30'),
(150, 'compost_divert', 'compost_divert.png', 3, 'Put it in your Home Compost Bin', 'A number of organizations, including the Department of Sanitation, environmental groups and the city''s botanical gardens, offer instruction on how New Yorkers can compost safely in small spaces. Many community gardens also maintain compost bins.', 0, 0, 191, 0, 0, 745000, NULL, 0, 0, 0, 0, '2007-11-12 17:04:06'),
(190, 'next', 'next.png', 1, NULL, NULL, 0, 0, 200, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(191, 'next', 'next.png', 1, NULL, NULL, 0, 0, 200, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 15:05:38'),
(192, 'next', 'next.png', 1, NULL, NULL, 0, 0, 200, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 15:06:21'),
(200, 'diaper_reduce', 'diaper_reduce.png', 1, 'Swear off Disposables', 'You can embark on a psychologically questionable program of very early toilet training or switch to cloth diapers.', 0, 0, 260, 0, 0, 116480, NULL, 0, 0, 0, 0, '2007-11-12 13:49:16'),
(200, 'diaper_sorted', 'diaper_sorted.png', 2, 'Sort for Recycling', 'Actually, some disposable diapers can be composted, though perhaps not in your local community garden.', 0, 0, 240, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 16:09:19'),
(200, 'diaper_reuse', 'diaper_reuse.png', 3, 'Use it Again!', 'Scrape it clean and put it right back. Why not?', 0, 0, 230, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 13:49:16'),
(200, 'diaper_unsorted', 'diaper_unsorted.png', 5, 'Toss it in the Can', 'The average American infant goes through 1,800 to 2,000 diapers every year.', 0, 0, 261, 0, 116480, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:32:49'),
(230, 'diaper_reduce', 'diaper_reduce.png', 3, 'Swear off Disposables', 'You can embark on a psychologically questionable program of very early toilet training or switch to cloth diapers.', 0, 0, 260, 0, 0, 116480, NULL, 0, 0, 0, 0, '2007-11-12 13:49:16'),
(230, 'diaper_unsorted', 'diaper_unsorted.png', 5, 'Toss it in the Can', 'The average American infant goes through 1,800 to 2,000 diapers every year.', 0, 0, 261, 0, 116480, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:34:43'),
(240, 'diaper_reduce', 'diaper_reduce.png', 3, 'Swear off Disposables', 'You can embark on a psychologically questionable program of very early toilet training or switch to cloth diapers.', 0, 0, 260, 0, 0, 116480, NULL, 0, 0, 0, 0, '2007-11-13 18:15:14'),
(240, 'diaper_unsorted', 'diaper_unsorted.png', 5, 'Toss it in the Can', 'The average American infant goes through 1,800 to 2,000 diapers every year.', 0, 0, 261, 0, 116480, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:34:43'),
(260, 'next', 'next.png', 1, NULL, NULL, 0, 0, 270, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(261, 'next', 'next.png', 1, NULL, NULL, 0, 0, 270, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 15:06:21'),
(270, 'paper_reuse', 'paper_reuse.png', 1, 'Use it for a Grocery List', 'More than half of waste paper generated in the city is thrown out. That''s out of 1 million tons annually. ', 0, 0, 290, 0, 0, 500000, NULL, 0, 0, 0, 0, '2007-11-14 11:17:39'),
(270, 'paper_unsorted', 'paper_unsorted.png', 2, 'Toss it in the Can', 'Nationwide, residents receive 4 million tons of junk mail annually, most of which ends up in a landfill. In the United States enough office and writing paper is thrown away annually to build a wall 12 feet high stretching from New York City to Los Angeles.', 0, 200, 322, 0, 1000000, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:34:43'),
(270, 'paper_sorted', 'paper_sorted.png', 3, 'Sort for Recycling', 'Enough paper is recycled in the United States daily to fill a 15-mile long train of boxcars.', 0, 300, 323, 1000000, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:45:35'),
(290, 'paper_unsorted', 'paper_unsorted.png', 1, 'Toss it in the Can', 'Nationwide, residents receive 4 million tons of junk mail annually, most of which ends up in a landfill. In the United States enough office and writing paper is thrown away annually to build a wall 12 feet high stretching from New York City to Los Angeles.', 0, 200, 320, 0, 500000, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:34:43'),
(290, 'paper_sorted', 'paper_sorted.png', 2, 'Sort for Recycling', 'Enough paper is recycled in the United States daily to fill a 15-mile long train of boxcars.', 0, 300, 321, 500000, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:45:35'),
(320, 'next', 'next.png', 1, NULL, NULL, 0, 0, 330, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(321, 'next', 'next.png', 1, NULL, NULL, 0, 0, 330, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 15:06:21'),
(322, 'next', 'next.png', 1, NULL, NULL, 0, 0, 330, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 15:06:21'),
(323, 'next', 'next.png', 1, NULL, NULL, 0, 0, 330, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 15:06:21'),
(330, 'ewaste_unsorted', 'ewaste_unsorted.png', 1, 'Toss it in the Can', 'Nearly 25,000 tons of electronic waste are thrown out in New York City annually. Improper disposal of e-waste is responsible for up to 70 percent of the toxic heavy metals in landfills.', 0, 0, 380, 0, 158, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:34:43'),
(330, 'ewaste_divert2', 'ewaste_divert2.png', 2, 'Bring it to an Electronics<br /> Recycling Drop Site', 'Advocates claim these programs are extremely successful. The Lower East Side Ecology Center has collected over 92 tons of electronics from New Yorkers who have come to 11 collection events organized so far in 2007.', 0, 0, 381, 0, 79, 79, NULL, 0, 0, 0, 0, '2007-11-13 15:24:32'),
(330, 'ewaste_reuse', 'ewaste_reuse.png', 3, 'Donate to Domestic<br /> Violence Charity', 'Charities, particularly groups working with victims of domestic violence, collect electronics for reuse or recycled parts. ', 0, 0, 382, 0, 79, 79, NULL, 0, 0, 0, 0, '2007-11-13 15:25:12'),
(330, 'ewaste_divert', 'ewaste_divert.png', 4, 'Return it to my Provider', 'New York City residents buy almost 12 million electronic devices, or 92,000 tons, annually. A state statute requires cell phone stores to accept as many as 10 phones per person annually for recycling.', 0, 0, 383, 0, 0, 158, NULL, 0, 0, 0, 0, '2007-11-12 14:54:54'),
(380, 'next', 'next.png', 1, NULL, NULL, 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 14:11:24'),
(381, 'next', 'next.png', 1, NULL, NULL, 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 15:06:21'),
(382, 'next', 'next.png', 1, NULL, NULL, 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 15:06:21'),
(383, 'next', 'next.png', 1, NULL, NULL, 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 15:06:21'),
(390, 'plastic', 'bottle.png', 1, '', NULL, 0, 0, 9030, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 14:29:35'),
(390, 'towel', 'towel.png', 2, '', NULL, 0, 0, 9100, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-13 12:06:51'),
(390, 'compost', 'compost.png', 3, '', NULL, 0, 0, 9150, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 14:20:58'),
(390, 'diaper', 'diaper.png', 4, '', NULL, 0, 0, 9200, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 14:20:58'),
(390, 'paper', 'paper.png', 5, '', NULL, 0, 0, 9270, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-13 12:06:51'),
(390, 'ewaste', 'ewaste.png', 6, '', NULL, 0, 0, 9330, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 14:21:22'),
(390, 'next', 'next.png', 13, 'Move on', '', 0, 0, 400, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 14:27:34'),
(400, 'next', 'next.png', 1, NULL, NULL, 0, 0, 410, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(410, 'truck_locally', 'truck_local.png', 1, 'Truck Locally', 'The Bloomberg administration and some Manhattan officials and residents are at loggerheads over whether a recycling center should be built on the Gansevoort peninsula in Hudson River Park. Much of the city''s recyclables are handled in neighborhoods in the outer boroughs. The administration says that taking recyclables to local stations in each of the boroughs, including Manhattan, would consume less energy and  reduce pollution.', 0, 0, 450, 0, 0, 0, 'sorted', 2.53, 0, 0, 0, '2007-11-12 20:31:18'),
(410, 'truck_nj', 'truck_nj.png', 2, 'Truck to Jersey', 'Most of Manhattan''s recyclables stay on the sanitation truck that collects them at curbside until they reach New Jersey, where they are processed. This accounts for an estimated 700,000 truck trips a year.', 0, 0, 455, 0, 0, 0, 'sorted', 6.66, 0, 0, 0, '2007-11-12 20:27:54'),
(410, 'truck_outerborough', 'truck_williamsburg.png', 3, 'Truck to Outer Borough', 'Trucking recyclable materials to the outer boroughs,advocates contend, unfairly burdens certain neighborhoods with the city''s trash as well as the health and environmental hazards that go along with it. Many of these centers are concentrated in poorer residential neighborhoods.', 0, 0, 457, 0, 0, 0, 'sorted', 11.4, 0, 0, 0, '2007-11-14 12:23:14'),
(450, 'next', 'next.png', 1, NULL, NULL, 0, 0, 460, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(455, 'next', 'next.png', 1, NULL, NULL, 0, 0, 510, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(457, 'next', 'next.png', 1, NULL, NULL, 0, 0, 560, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-08 15:15:29'),
(460, 'barge_citywide', 'barge_citywide.png', 1, 'Barge to Citywide Center', 'The city has established a 20-year contract with the Sims Group to build a large citywide recycling center in Sunset Park. The citywide facility costs an estimated $45 million and will create about 160 construction jobs and 100 permanent jobs. Putting materials on a barge and sending them down the East River produces fewer emissions in the city than shipping the material on trucks.', 0, 0, 501, 0, 0, 0, 'sorted', 0, 0, 0, 6.4, '2007-11-12 20:40:56'),
(460, 'barge_outside_city', 'barge_outside_city.png', 2, 'Barge to Center Outside City', 'The city plans on eliminating about 55,000 vehicle miles by transporting recyclables by barge or rail. But in transporting recyclables to a processing center outside of the city via barge, New York is still exporting its waste.', 0, 0, 500, 0, 0, 0, 'sorted', 0, 0, 0, 5.54, '2007-11-12 20:40:56'),
(460, 'truck_verzano', 'truck_verrazano.png', 3, 'Truck to Citywide Center', 'Trucking recyclables over bridges and through the boroughs, some environmentalists argue, pollutes residential neighborhoods and creates health problems, like asthma. The city wants to phase out trucking from borough to borough but has not yet met that goal.', 0, 0, 501, 0, 0, 0, 'sorted', 0, 0, 0, 0, '2007-11-12 20:40:56'),
(500, 'next', 'next.png', 1, NULL, NULL, 0, 0, 510, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-07 19:01:55'),
(501, 'next', 'next.png', 1, NULL, NULL, 0, 0, 515, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 16:08:37'),
(510, 'barge_ocean', 'barge_ocean.png', 1, 'Barge to Asia', 'Most of the city''s recycled raw materials are exported. Because of a shortage of forestry resources in countries like China, Japan and Taiwan, paper exports from the United States are highly desirable. The largest export from the Port of New York and New Jersey is scrap paper. International ship emissions account for more than 14 percent of nitrogen emissions and over 16 percent of sulfur emissions worldwide. Today''s large cargo ships can release as much pollution in one hour as 350,000 current cars.', 0, 0, 660, 0, 0, 0, 'sorted', 0, 0, 0, 13584, '2007-11-14 11:17:39'),
(510, 'barge_citywide', 'barge_citywide.png', 2, 'Manufactured in City', 'When paper is processed at a private paper-recycling center on Staten Island, the city collects taxes at almost every stage. Some claim by exporting the paper, the city loses revenue.', 0, 0, 660, 0, 0, 0, 'sorted', 0, 0, 0, 14.218, '2007-11-12 20:40:56'),
(510, 'train_garbage', 'train_garbage.png', 3, 'Rail Throughout Country', 'Materials can also be packed in railcars and sent to manufacturers across the country. That diverts manufacturing revenues from the city. Some officials contend the cost of doing business in New York City makes it difficult to process raw materials here.', 0, 0, 660, 0, 0, 0, 'sorted', 0, 0, 383, 0, '2007-11-12 21:23:01'),
(515, 'barge_ocean', 'barge_ocean.png', 1, 'Barge to Asia', 'Most of the city''s recycled raw materials are exported. Because of a shortage of forestry resources in countries like China, Japan and Taiwan, paper exports from the United States are highly desirable. The largest export from the Port of New York and New Jersey is scrap paper. International ship emissions account for more than 14 percent of nitrogen emissions and over 16 percent of sulfur emissions worldwide. Today''s large cargo ships can release as much pollution in one hour as 350,000 current cars.', 0, 0, 660, 0, 0, 0, 'sorted', 0, 0, 0, 13584, '2007-11-14 11:17:40'),
(515, 'barge_citywide', 'barge_citywide.png', 2, 'Manufactured in City', 'When paper is processed at a private paper-recycling center on Staten Island, the city collects taxes at almost every stage. Some claim by exporting the paper, the city loses revenue.', 0, 0, 660, 0, 0, 0, 'sorted', 0, 0, 0, 14.218, '2007-11-12 20:40:56'),
(515, 'train_garbage', 'train_garbage.png', 3, 'Rail Throughout Country', 'Materials can also be packed in railcars and sent to manufacturers across the country. That diverts manufacturing revenues from the city. Some officials contend the cost of doing business in New York City makes it difficult to process raw materials here.', 0, 0, 660, 0, 0, 0, 'sorted', 0, 0, 383, 0, '2007-11-12 21:23:01'),
(560, 'barge_citywide', 'barge_citywide.png', 1, 'Barge to Citywide Center', 'The city has established a 20-year contract with the Sims Group to build a large citywide recycling center in Sunset Park. The citywide facility costs an estimated $45 million and will create about 160 construction jobs and 100 permanent jobs. Putting materials on a barge and sending the down the East River produces fewer emissions in the city than shipping the material on trucks.', 0, 0, 600, 0, 0, 0, 'sorted', 0, 0, 0, 8.539, '2007-11-12 20:42:07'),
(560, 'barge_ocean', 'barge_ocean.png', 2, 'Barge to Processing Center out of City', 'The city plans on eliminating about 55,000 vehicle miles by transporting recyclables by barge or rail. But in transporting recyclables to a processing center outside of the city via barge, New York is still exporting its waste. ', 0, 0, 600, 0, 0, 0, 'sorted', 0, 0, 0, 8.6359, '2007-11-12 20:42:07'),
(560, 'truck_williamsburg', 'truck_williamsburg.png', 3, 'Truck to Citywide Center', 'Trucking recyclables over bridges and through the boroughs, some environmentalists argue, pollutes residential neighborhoods and creates health problems, like asthma. The city wants to phase out trucking from borough to borough but has not yet met that goal.', 0, 0, 600, 0, 0, 0, 'sorted', 7.71, 0, 0, 0, '2007-11-12 20:42:07'),
(600, 'next', 'next.png', 1, NULL, NULL, 0, 0, 610, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-07 19:49:14'),
(610, 'barge_ocean', 'barge_ocean.png', 1, 'Barge to Asia', 'Most of the city''s recycled raw materials are exported. Because of a shortage of forestry resources in countries like China, Japan and Taiwan, paper exports from the United States are highly desirable. The largest export from the Port of New York and New Jersey is scrap paper. International ship emissions account for more than 14 percent of nitrogen emissions and over 16 percent of sulfur emissions worldwide. Today''s large cargo ships can release as much pollution in one hour as 350,000 current cars.', 0, 0, 660, 0, 0, 0, 'sorted', 0, 0, 0, 13584, '2007-11-12 20:42:07'),
(610, 'barge_citywide', 'barge_citywide.png', 2, 'Sell to a NYC Manufacturer', 'When paper is processed at a private paper-recycling center on Staten Island, the city collects taxes at almost every stage. Some claim by exporting, the city loses revenue. ', 0, 0, 660, 0, 0, 0, 'sorted', 0, 0, 0, 14.218, '2007-11-12 20:42:07'),
(610, 'train_garbage', 'train_garbage.png', 3, 'Sell to U.S. Manufacturer', 'Materials can also be packed in railcars and sent to manufacturers across the country. That diverts manufacturing revenues from the city. Some officials contend the cost of doing business in New York City makes it difficult to process raw materials here.', 0, 0, 660, 0, 0, 0, 'sorted', 0, 0, 383, 0, '2007-11-12 21:23:01'),
(660, 'next', 'next.png', 1, NULL, NULL, 0, 0, 670, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-07 20:05:02'),
(670, 'truck_verrazano', 'truck_verrazano.png', 1, 'Take it to Fresh Kills', 'The former landfill on Staten Island that was closed in 2001, Fresh Kills is one of only two man-made structures that can be seen from space. The other is the Great Wall of China. Fresh Kills is being developed as a park now.', 0, 0, 770, 0, 0, 0, 'unsorted', 22.45, 0, 0, 0, '2007-11-14 11:14:01'),
(670, 'marine_transfer', 'marine_transfer.png', 2, 'Truck to Station in Outer Boroughs', 'After Fresh Kills was closed in 2001, the city''s trash went to transfer stations in the Bronx or Brooklyn. The new system cost the city 50 percent more than dumping the garbage in Fresh Kills. Advocates and environmentalists claim the concentration of stations in the outer boroughs amounts to environmental discrimination.', 0, 0, 710, 0, 0, 0, 'unsorted', 10.25, 0, 0, 0, '2007-11-12 20:42:35'),
(670, 'truck_williamsburg', 'truck_williamsburg.png', 3, 'Truck it to a Local Transfer Station', 'New York City throws out enough garbage every day to fill the Empire State Building. For much of it, the first stop is at a station where it can be transferred to a railcar or barge. The city''s current plan calls for greater use of local transfer stations.', 0, 0, 710, 0, 0, 0, 'unsorted', 5.88, 0, 0, 0, '2007-11-12 20:43:29'),
(710, 'next', 'next.png', 1, NULL, NULL, 0, 0, 720, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-07 20:26:43'),
(720, 'landfill', 'landfill.png', 1, 'Private Landfill', 'The city throws away 24 million pounds of household trash each day, which, according to some estimates, costs about $167 per ton to send to an out-of-state landfill or incinerator. Most of the trash is trucked to landfills upstate, or to Pennsylvania, Ohio or Virginia.', 0, 0, 770, 0, 0, 0, 'unsorted', 0, 73, 0, 0, '2007-11-12 20:43:29'),
(720, 'conveyer_belt', 'conveyer_belt.png', 2, 'Materials Recovery Facility', 'Instead of separating your trash into a plastic, metal, glass, paper and non-recyclable piles you could lump them all together and send them to a nearby materials recovery facility. Here the waste is passed to a private contractor and separated. Based on other models in the country, it would cost a total of $153 per ton to do this here. About 90 percent of the material that enters this type of facility, is processed and can be resold.', 0, 0, 770, 0, 0, 0, 'unsorted', 0, 8.19, 0, 0, '2007-11-12 20:43:29'),
(720, 'incinerator', 'incinerator.png', 3, 'Incinerator in New Jersey', 'New York State is the top waste exporter in the country at 4.2 million tons a year. Like out of state landfills, incinerators cost the city, from curbside to export, an estimated $167 per ton. According to one estimate, Newark''s incinerator receives 1,700 tons of waste from Manhattan daily.', 0, 0, 770, 0, 0, 0, 'unsorted', 0, 8.19, 0, 0, '2007-11-12 20:43:29'),
(720, 'energy_plant', 'energy_plant.png', 4, 'Waste to Energy Plant', 'While the city stopped considering a waste to energy plant after a very controversial proposal by Mayor Ed Koch in the early ''80s, plants on Long Island have proved to be successful and less environmentally costly than thought two decades ago. One in Hempstead burns 900,000 tons of garbage annually and powers itself as well as 65,000 adjacent homes. ', 0, 0, 770, 0, 0, 0, 'unsorted', 0, 8.19, 0, 0, '2007-11-12 20:43:29'),
(770, 'next', 'next.png', 1, NULL, NULL, 0, 0, 780, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-07 20:47:05'),
(780, 'next', 'next.png', 1, '', '', 0, 0, 790, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 19:04:07'),
(790, 'show_form', 'next.png', 1, NULL, NULL, 0, 0, 790, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-13 21:44:20'),
(9030, 'plastic_reuse', 'plastic_reuse.png', 2, 'Refill Use Again', 'In 2006, Americans bought 50 billion water bottles - 167 for every person in the country. About 38 billion of those bottles ended up in a landfill.', 0, 0, 9060, 0, 0, 13258, NULL, 0, 0, 0, 0, '2007-11-14 11:07:39'),
(9030, 'plastic_reduce', 'plastic_reduce.png', 1, 'Don''t Drink Bottled Water', 'Approximately 25 percent of all bottled water is municipal tap water. New York''s water is so pure - it originates in streams upstate - that it does not need to be filtered.  It costs 49 cents a year to use New York City tap water, while it costs $1,400 a year to purchase bottled water.', 0, 0, 9090, 0, 0, 17677, NULL, 0, 0, 0, 0, '2007-11-14 11:07:39'),
(9030, 'plastic_unsorted', 'plastic_unsorted.png', 2, 'Toss it in the Can', 'Nationwide, 2.5 million plastic bottles are thrown away every hour.', 0, 0, 9099, 0, 17677, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:38:44'),
(9030, 'plastic_sorted', 'paper_sorted.png', 1, 'Sort for Recycling', 'Nationwide, 25 percent of plastic bottles are recycled. Of all the glass, metal and plastics collected for recycling in the city, plastics make up about 13 percent. For residences, the city''s waste diversion rate for recycling is about 18 percent. The rate could be as a high as 36 percent, but 50 percent of materials that could be recycled are thrown out with the regular trash.', 0, 0, 9097, 17677, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:40:10'),
(9060, 'plastic_sorted', 'paper_sorted.png', 1, 'Sort for Recycling', 'Nationwide, 25 percent of plastic bottles are recycled. Of all the glass, metal and plastics collected for recycling in the city, plastics make up about 13 percent. For residences, the city''s waste diversion rate for recycling is about 18 percent. The rate could be as a high as 36 percent, but 50 percent of materials that could be recycled are thrown out with the regular trash.', 0, 0, 9096, 4420, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:38:44'),
(9060, 'plastic_unsorted', 'plastic_unsorted.png', 2, 'Toss it in the Can', 'Nationwide, 2.5 million plastic bottles are thrown away every hour.', 0, 0, 9095, 0, 4420, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:38:44'),
(9090, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9095, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9096, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9097, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9099, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9100, 'towel_unsorted', 'towel_unsorted.png', 2, 'Toss it in the Garbage', 'New Yorkers throw away 18,556 tons of towels, sheets and pillowcases and a total of about 190,000 tons of recyclable textiles a year.', 0, 0, 9145, 0, 18556, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:38:44'),
(9100, 'towel_divert', 'towel_divert.png', 3, 'Drop it off at Goodwill', 'One person''s garbage is another one''s gold. You may be sick of that chartreuse terry cloth but it could be just the thing for another New Yorker. Eventually, getting rid of it will be that person''s responsibility.', 0, 0, 9140, 0, 9278, 9278, NULL, 0, 0, 0, 0, '2007-11-12 18:47:50'),
(9100, 'towel_reuse', 'towel_reuse.png', 1, 'Reuse it as a Rag', 'This will keep it out of the landfill a while longer and save you the expense of buying sponges, paper towels and Swiffers.', 0, 0, 9140, 0, 9278, 9278, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(9140, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9145, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9150, 'compost_sorted', 'compost_sorted.png', 2, 'Sort it for Curbside Pickup', 'The Department of Sanitation currently collects limited amounts of yard waste, fall leaves and Christmas trees. If New Yorkers went all out and composted food scraps and other compostables with our yard waste, up to 30 percent of the city''s refuse by some counts could avoid the landfill.', 0, 0, 9192, 745000, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:44:30'),
(9150, 'compost_unsorted', 'compost_unsorted.png', 1, 'Toss it in the Can', 'Food waste accounts for about 22 percent of all residential garbage thrown away in NYC, with lawn clippings, dried leaves, branches and the like making up another 6 to 7.', 0, 0, 9190, 0, 745000, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:38:44'),
(9150, 'compost_divert', 'compost_divert.png', 3, 'Put it in your Home Compost Bin', 'A number of organizations, including the Department of Sanitation, environmental groups and the city''s botanical gardens, offer instruction on how New Yorkers can compost safely in small spaces. Many community gardens also maintain compost bins.', 0, 0, 9191, 0, 0, 745000, NULL, 0, 0, 0, 0, '2007-11-14 15:38:44'),
(9190, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9191, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9192, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9200, 'diaper_reuse', 'diaper_reuse.png', 3, 'Use it Again!', 'Scrape it clean and put it right back. Why not?', 0, 0, 9230, 0, 0, 0, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(9200, 'diaper_reduce', 'diaper_reduce.png', 1, 'Swear off Disposables', 'You can embark on a psychologically questionable program of very early toilet training or switch to cloth diapers.', 0, 0, 9260, 0, 0, 116480, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(9200, 'diaper_unsorted', 'diaper_unsorted.png', 5, 'Toss it in the Can', 'The average American infant goes through 1,800 to 2,000 diapers every year.', 0, 0, 9261, 0, 116480, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:43:27'),
(9200, 'diaper_sorted', 'diaper_sorted.png', 2, 'Sort for Recycling', 'Actually, some disposable diapers can be composted, though perhaps not in your local community garden.', 0, 0, 9240, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:43:27'),
(9230, 'diaper_unsorted', 'diaper_unsorted.png', 5, 'Toss it in the Can', 'The average American infant goes through 1,800 to 2,000 diapers every year.', 0, 0, 9261, 0, 116480, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:43:27'),
(9230, 'diaper_reduce', 'diaper_reduce.png', 3, 'Swear off Disposables', 'You can embark on a psychologically questionable program of very early toilet training or switch to cloth diapers.', 0, 0, 9260, 0, 0, 116480, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(9240, 'diaper_unsorted', 'diaper_unsorted.png', 5, 'Toss it in the Can', 'The average American infant goes through 1,800 to 2,000 diapers every year.', 0, 0, 9261, 0, 116480, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:43:27'),
(9240, 'diaper_reduce', 'diaper_reduce.png', 3, 'Swear off Disposables', 'You can embark on a psychologically questionable program of very early toilet training or switch to cloth diapers.', 0, 0, 9260, 0, 0, 116480, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(9260, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9261, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9270, 'paper_unsorted', 'paper_unsorted.png', 2, 'Toss it in the Can', 'Nationwide, residents receive 4 million tons of junk mail annually, most of which ends up in a landfill. In the United States enough office and writing paper is thrown away annually to build a wall 12 feet high stretching from New York City to Los Angeles.', 0, 200, 9322, 0, 1000000, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:43:27'),
(9270, 'paper_reuse', 'paper_reuse.png', 1, 'Use it for a Grocery List', 'More than half of waste paper generated in the city is thrown out. That''s out of 1 million tons annually. ', 0, 0, 9290, 0, 0, 500000, NULL, 0, 0, 0, 0, '2007-11-12 18:47:50'),
(9270, 'paper_sorted', 'paper_sorted.png', 3, 'Sort for Recycling', 'Enough paper is recycled in the United States daily to fill a 15-mile long train of boxcars.', 0, 300, 9323, 1000000, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:43:27'),
(9290, 'paper_unsorted', 'paper_unsorted.png', 1, 'Toss it in the Can', 'Nationwide, residents receive 4 million tons of junk mail annually, most of which ends up in a landfill. In the United States enough office and writing paper is thrown away annually to build a wall 12 feet high stretching from New York City to Los Angeles.', 0, 200, 9320, 0, 500000, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:43:27'),
(9290, 'paper_sorted', 'paper_sorted.png', 2, 'Sort for Recycling', 'Enough paper is recycled in the United States daily to fill a 15-mile long train of boxcars.', 0, 300, 9321, 500000, 0, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:43:27'),
(9320, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9321, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9322, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9323, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9330, 'ewaste_divert', 'ewaste_divert.png', 4, 'Return it to my Provider', 'New York City residents buy almost 12 million electronic devices, or 92,000 tons, annually. A state statute requires cell phone stores to accept as many as 10 phones per person annually for recycling.', 0, 0, 9383, 0, 0, 158, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(9330, 'ewaste_divert2', 'ewaste_divert2.png', 2, 'Bring it to an Electronics Recycling Drop Site', 'Advocates claim these programs are extremely successful. The Lower East Side Ecology Center has collected over 92 tons of electronics from New Yorkers who have come to 11 collection events organized so far in 2007.', 0, 0, 9381, 0, 79, 79, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(9330, 'ewaste_unsorted', 'ewaste_unsorted.png', 1, 'Toss it in the Can', 'Nearly 25,000 tons of electronic waste are thrown out in New York City annually. Improper disposal of e-waste is responsible for up to 70 percent of the toxic heavy metals in landfills.', 0, 0, 9380, 0, 158, 0, NULL, 0, 0, 0, 0, '2007-11-14 15:43:27'),
(9330, 'ewaste_reuse', 'ewaste_reuse.png', 3, 'Donate to Domestic Violence Charity', 'Charities, particularly groups working with victims of domestic violence, collect electronics for reuse or recycled parts. ', 0, 0, 9382, 0, 79, 79, NULL, 0, 0, 0, 0, '0000-00-00 00:00:00'),
(9380, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9381, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9382, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08'),
(9383, 'next', 'next.png', 1, '', '', 0, 0, 390, 0, 0, 0, NULL, 0, 0, 0, 0, '2007-11-12 20:18:08');

-- --------------------------------------------------------

--
-- Table structure for table `images_central`
--

CREATE TABLE IF NOT EXISTS `images_central` (
  `rec_order` int(11) NOT NULL default '0' COMMENT 'Corresponds to text_input screen on which to be displayed',
  `image_name` varchar(100) NOT NULL default '',
  `file_name` varchar(100) NOT NULL default '' COMMENT 'Reserved for future use',
  `pos_x` int(11) NOT NULL default '0',
  `pos_y` int(11) NOT NULL default '0',
  `timestamp` timestamp NOT NULL default '0000-00-00 00:00:00' on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`rec_order`,`image_name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `images_central`
--

INSERT INTO `images_central` (`rec_order`, `image_name`, `file_name`, `pos_x`, `pos_y`, `timestamp`) VALUES
(30, 'plastic_bottle', 'central_bottle.png', 0, 0, '2007-11-07 22:16:31'),
(50, 'plastic_reduce', 'central_bottle.png', 0, 0, '2007-11-07 22:16:31'),
(60, 'plastic_reuse', 'central_bottle.png', 0, 0, '2007-11-07 22:16:31'),
(90, 'plastic_bottle', 'central_bottle.png', 0, 0, '0000-00-00 00:00:00'),
(95, 'plastic_bottle', 'central_bottle.png', 0, 0, '0000-00-00 00:00:00'),
(96, 'plastic_bottle', 'central_bottle.png', 0, 0, '2007-11-13 16:27:34'),
(97, 'plastic_bottle', 'central_bottle.png', 0, 0, '0000-00-00 00:00:00'),
(99, 'plastic_bottle', 'central_bottle.png', 0, 0, '0000-00-00 00:00:00'),
(100, 'towel', 'central_towel.png', 0, 0, '0000-00-00 00:00:00'),
(140, 'towel', 'central_towel.png', 0, 0, '2007-11-13 16:26:09'),
(145, 'towel', 'central_towel.png', 0, 0, '0000-00-00 00:00:00'),
(150, 'compost', 'central_compost.png', 0, 0, '0000-00-00 00:00:00'),
(190, 'compost', 'central_compost.png', 0, 0, '2007-11-13 16:31:40'),
(191, 'compost', 'central_compost.png', 0, 0, '2007-11-13 16:31:03'),
(192, 'compost', 'central_compost.png', 0, 0, '2007-11-13 16:31:08'),
(200, 'diaper', 'central_diaper.png', 0, 0, '2007-11-13 16:33:41'),
(230, 'diaper', 'central_diaper.png', 0, 0, '2007-11-13 16:32:12'),
(240, 'diaper', 'central_diaper.png', 0, 0, '2007-11-13 16:32:20'),
(260, 'diaper', 'central_diaper.png', 0, 0, '0000-00-00 00:00:00'),
(261, 'diaper', 'central_diaper.png', 0, 0, '2007-11-13 16:32:35'),
(270, 'paper', 'central_paper.png', 0, 0, '0000-00-00 00:00:00'),
(290, 'paper', 'central_paper.png', 0, 0, '0000-00-00 00:00:00'),
(320, 'paper', 'central_paper.png', 0, 0, '0000-00-00 00:00:00'),
(321, 'paper', 'central_paper.png', 0, 0, '2007-11-13 16:34:06'),
(322, 'paper', 'central_paper.png', 0, 0, '2007-11-13 16:34:26'),
(323, 'paper', 'central_paper.png', 0, 0, '2007-11-13 16:34:26'),
(330, 'ewaste', 'central_cell_phone.png', 0, 0, '0000-00-00 00:00:00'),
(380, 'ewaste', 'central_cell_phone.png', 0, 0, '2007-11-13 16:35:19'),
(381, 'ewaste', 'central_cell_phone.png', 0, 0, '2007-11-13 16:35:59'),
(382, 'ewaste', 'central_cell_phone.png', 0, 0, '2007-11-13 16:35:59'),
(383, 'ewaste', 'central_cell_phone.png', 0, 0, '2007-11-13 16:35:59');

-- --------------------------------------------------------

--
-- Table structure for table `text_input`
--

CREATE TABLE IF NOT EXISTS `text_input` (
  `rec_order` int(11) NOT NULL default '0' COMMENT 'Primary screen ID; used to assign images_buttons records',
  `layout_template` int(11) NOT NULL default '1' COMMENT 'Determines which Template definitions section is used in CSS file',
  `change_choices` enum('y','n') NOT NULL default 'n' COMMENT 'Indicate if this is a summary screen when user can change choices.',
  `short_text` varchar(255) NOT NULL default '' COMMENT 'Not used; for comments only',
  `text_content` mediumtext NOT NULL COMMENT 'Text displayed on screen.  Wrap in <p></p>.',
  `bg_image` varchar(100) default NULL COMMENT 'Background image for screen',
  `bg_pos_x` int(11) NOT NULL default '0',
  `bg_pos_y` int(11) NOT NULL default '0',
  `timestamp` timestamp NOT NULL default '0000-00-00 00:00:00' on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`rec_order`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `text_input`
--

INSERT INTO `text_input` (`rec_order`, `layout_template`, `change_choices`, `short_text`, `text_content`, `bg_image`, `bg_pos_x`, `bg_pos_y`, `timestamp`) VALUES
(10, 1, 'n', 'Introduction - THIS IS THE TITLE PAGE.', '', 'bg_1.jpg', 0, 0, '2007-11-14 12:31:15'),
(12, 1, 'n', 'Introduction', '<p>What did you throw in a trash can today? You probably did not give it much thought. But this week New Yorkers threw away 64,000 tons of garbage. That comes out to almost 7 billion pounds of garbage every year.</p>\r\n<p>Whisking off the detritus of our daily lives costs the city more than a billion dollars a year. </p>', 'bg_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(14, 1, 'n', 'Introduction', '<p>Thousands of trucks, belching diesel fumes, carry our banana peels, battered tennis balls and discarded deli containers from one part of the city to another. Trucks, trains and barges haul our waste to landfills and recycling centers in other states &mdash; and other continents.</p>', 'bg_3.jpg', 0, 0, '2007-11-14 12:31:15'),
(24, 1, 'n', 'Introduction', '<p class="centered">No one wants garbage.<br /> No one wants to think about it.<br /> No one wants to pay for it.<br />\r\nBut it isn''t going away.</p>\r\n\r\n<p>Can you create a garbage plan for New York City? What do you do with your household garbage? How should the city handle it? Can you keep New York from drowning in our own refuse?</p>\r\n\r\n<p>Play the Garbage Game. Begin by sorting your own waste. What would you throw unsorted into the garbage can, recycle for curbside pickup -- or keep from going into the trash altogether?</p>', 'bg_5.jpg', 0, 0, '2007-11-14 12:31:15'),
(30, 1, 'n', 'Screen: Plastic', '<p>You''ve quenched your thirst, but you are left with an empty plastic bottle. Select the button below that best reflects what you would do with the empty plastic water bottles.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(60, 1, 'n', 'Screen: Plastic Loopback', '<p>Eventually that bottle will be too bruised to reuse. When that time comes, where will you put it?</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(90, 1, 'n', 'Screen: Plastic Followup - reduce', '<p>You are off to a good start, you started with zero waste -- and you still have no waste.</p>\r\n<p>Every New York City household recycles about 2.9 pounds of plastics, metals and glass per week. About half of the plastics collected from the city for recycling are made up of recyclable polyethylene terephthalate, which is what water and soda bottles are made from.  But forget about the bottles. Some New York City officials want residents to give up their Dasani entirely and drink from the faucet.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(95, 1, 'n', 'Screen: Plastic Followup - reuse-trash', '<p>We figure that a bottle will get refilled about three times on average, so we''ve reduced the volume of water bottle waste in your unsorted garbage to 25 percent of the 17,677 tons that New Yorkers currently generate each year, or 4,420 tons.</p>\r\n<p>Every New York City household recycles about 2.9 pounds of plastics, metals and glass per week. About half of the plastics collected from the city for recycling are made up of recyclable polyethylene terephthalate, which is what water and soda bottles are made from. But forget about the bottles. Some New York City officials want residents to give up their Dasani entirely and drink from the faucet.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(96, 1, 'n', 'Screen: Plastic Followup - reuse-recycle', '<p>We figure that a bottle will get refilled about three times on average, so we''ve reduced the volume of water bottle waste in your sorted recycling to 25 percent of the 17,677 tons that New Yorkers currently generate each year, or 4,420 tons.</p>\r\n<p>Every New York City household recycles about 2.9 pounds of plastics, metals and glass per week. About half of the plastics collected from the city for recycling are made up of recyclable polyethylene terephthalate, which is what water and soda bottles are made from. But forget about the bottles. Some New York City officials want residents to give up their Dasani entirely and drink from the faucet.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(97, 1, 'n', 'Screen: Plastic Followup - recycle', '<p><b>17,677</b> tons of plastic bottles will land at the curb this year if New Yorkers keep up their disposable bottle habit. We''ve added <b>17,677</b> tons of water bottles to your sorted recycling pile.</p>\r\n<p>Every New York City household recycles about 2.9 pounds of plastics, metals and glass per week. About half of the plastics collected from the city for recycling are made up of recyclable polyethylene terephthalate, which is what water and soda bottles are made from. But forget about the bottles. Some New York City officials want residents to give up their Dasani entirely and drink from the faucet.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(99, 1, 'n', 'Screen: Plastic Followup - trash', '<p><b>17,677</b> tons of plastic bottles will land at the curb this year if New Yorkers keep up their disposable bottle habit. We''ve added <b>17,677</b> to your trash pile.</p>\r\n<p>Every New York City household recycles about 2.9 pounds of plastics, metals and glass per week. About half of the plastics collected from the city for recycling are made up of recyclable polyethylene terephthalate, which is what water and soda bottles are made from.  But forget about the bottles. Some New York City officials want residents to give up their Dasani entirely and drink from the faucet.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(100, 1, 'n', 'Screen: Towel', '<p>Your fraying bathroom towels are starting to wear you out, and the new ones you''ve bought go better with your d&eacute;cor anyway. What will you do with your old towel?</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(140, 1, 'n', 'Screen: Towel Followup - reuse', '<p>Clothing and textiles make up 5.7 percent of New York City''s garbage. New York City does not recycle or compost this material, although a garbage plan approved by City Council in 1992 called for recycling cloth. Beyond keeping your towel out of the trash for a while, using worn-out cloth for household chores reduces your use of paper towels and other disposable products. More than 90 percent of U.S. homes use paper towels, producing 3,000 tons of waste a day and destroying vast tracts of forest. Donating the cloth to Goodwill, which sells used items at thrift stores, also extends its use.</p>\r\n<p>We''ve added 9,278 tons to your unsorted garbage, a credit of 50 percent for ensuring that your towel will continue to be used.</p>\r\n', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(145, 1, 'n', 'Screen: Towel Followup - trash', '<p>Clothing and textiles make up 5.7 percent of New York City''s garbage. New York City currently does not recycle or compost this material, although a garbage plan approved by City Council in 1992 called for recycling cloth. Beyond keeping your towel out of the trash for a while, using worn-out cloth for household chores reduces your use of paper towels and other disposable products. More than 90 percent of U.S. homes use paper towels, producing 3,000 tons of waste a day and destroying vast tracts of forest.</p>\r\n\r\n<p>We''ve added 18,556 to your unsorted garbage.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(150, 1, 'n', 'screen: Compost', 'The farmer''s market had a bumper crop of apples this week. Now that you''ve munched your Honeycrisps down to the core, what will you do with what''s left?', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(190, 1, 'n', 'screen: Compost followup', '<p>Composting is the controlled decomposition of organic material so that it becomes soil. In Toronto, residents sort out compostable materials, which the city then processes to produce soil for farms and parks. So far, New York City does not do this, although it collects and composts leaves and some yard waste and runs a composting operation for food waste collected from jail kitchens on Riker''s Island. Some community gardens do compost food waste. </p>\r\n\r\n<p>New York City households throw away about 745,000 tons of food waste each year. We''ve added that volume to your unsorted garbage.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(191, 1, 'n', 'screen: Compost followup divert', '<p>Composting is the controlled decomposition of organic material so that it becomes soil. Although it ran a pilot composting program in the 1990s, the Department of Sanitation does not collect food waste from the general public for composting. Some individuals do compost, though and a number of community gardens run their own composting programs. Other cities have done more. In Toronto, residents sort out compostable materials. The city collects and processes the waste, producing soil for farms and parks. Officials hope the program will reduce the garbage headed to landfills by about 30 percent.</p>\r\n\r\n<p>We''ve added 745,000 tons of sloppy food scraps to the waste you''ve diverted from the municipal waste stream.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(192, 1, 'n', 'screen: Compost followup sort', '<p>New York City households throw away about 745,000 tons of food waste each year. We''ve added that volume to your sorted recycling.</p>\r\n\r\n<p>Composting is the controlled decomposition of organic material so that it becomes soil. In Toronto, residents sort out compostable materials, which the city then processes to produce soil for farms and parks. So far, New York City does not do this, although it collects and composts leaves and some yard waste and runs a composting operation for food waste collected from jail kitchens on Riker''s Island. Some community gardens do compost food waste.</p>\r\n', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(200, 1, 'n', 'screen: Diaper', '<p>Your baby woke up wailing with a dirty diaper. She''s sleeping soundly again, but you''re left holding a soiled Pamper.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(230, 1, 'n', 'Screen: Hard to Divert', '<p>We know you are just kidding about that. Seriously, how should we handle hard to divert waste like stinky diapers and old tennis balls?</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(240, 1, 'n', 'Screen: Hard to Divert', '<p>Some disposable diapers can be composted, but New York City doesn''t have any plans in the works to take diapers in a regular compost pickup.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(260, 1, 'n', 'Screen: diaper followup reduce', '<p>If you have a baby, you use diapers. About 90 percent of U.S. families opt for disposables. With the average baby going through about five a day, Americans throw away 3.6 million tons of diapers a year. Alternatives are emerging. Toronto accepts diapers for composting, but the city must separate out the plastic covering and send that to a landfill. Flushable diapers have come on the market. And many environmentally conscious parents opt for cloth. That decision reduces garbage in the landfill. But disposable diapers use 29 percent less energy than cloth diapers washed at home and less water as well.</p>\r\n\r\n<p>Since most parents use disposable diapers, New Yorkers throw away 116,480 tons of diapers a year. You''ve kept 100 percent of that out of the garbage</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(261, 1, 'n', 'Screen: diaper followup unsorted', '<p>If you have a baby, you use diapers. About 90 percent of U.S. families opt for disposables. With the average baby going through about five a day, Americans throw away 3.6 million tons of diapers a year. Alternatives are emerging. Toronto accepts diapers for composting, but the city must separate out the plastic covering and send that to a landfill. Flushable diapers have come on the market. And many environmentally conscious parents opt for cloth. That decision reduces garbage in the landfill. But disposable diapers use 29 percent less energy than cloth diapers washed at home and less water as well.</p>\r\n\r\n<p>New Yorkers throw away 116,480 tons of disposable diapers a year. We''ve increased your unsorted garbage by 116,480 tons.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(270, 1, 'n', 'Screen: Paper', '<p>You have received another piece of junk mail. Though the offer is enticing (well, not really), you now have to dispose of the paper. Would you:</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:35:56'),
(290, 1, 'n', 'Screen: Paper Loop', '<p>Kudos for reusing it. We''ll reduce your impact on the city''s waste stream -- its recycled trash and unsorted garbage -- by 50 percent, but now it really is refuse.  Will you ...</p>\r\n', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:35:36'),
(320, 1, 'n', 'Screen: paper followup reuse unsorted', '<p>The U.S. Postal Service processes 80 billion pieces of junk mail annually. In New York City, only 45 percent of paper  is recycled, totaling an estimated 366,000 to 423,000 tons a year or 4.2 pounds of paper per household weekly. When the city suspended plastic and glass recycling in 2002, a public outcry persuaded Mayor Michael Bloomberg to retain paper recycling. Half of the mixed paper collected by the Department of Sanitation goes to a number of private companies for processing. The rest goes to the Visy Paper Mill on Staten Island, where it is turned into linerboard for corrugated cardboard.</p>\r\n\r\n<p>We''ve added 500,000 tons of paper to your curbside garbage pile.</p> ', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(321, 1, 'n', 'Screen: paper followup reuse sorted', '<p>The U.S. Postal Service processes 80 billion pieces of junk mail annually. In New York City, only 45 percent of paper  is recycled, totaling an estimated 366,000 to 423,000 tons a year or 4.2 pounds of paper per household weekly. When the city suspended plastic and glass recycling in 2002, a public outcry persuaded Mayor Michael Bloomberg to retain paper recycling. Half of the mixed paper collected by the Department of Sanitation goes to a number of private companies for processing. The rest goes to the Visy Paper Mill on Staten Island, where it is turned into linerboard for corrugated cardboard.</p>\r\n\r\nWe''ve added 500,000 tons of paper to your sorted recycling. ', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(322, 1, 'n', 'Screen: paper followup unsorted', '<p>The U.S. Postal Service processes 80 billion pieces of junk mail annually. In New York City, only 45 percent of paper  is recycled, totaling an estimated 366,000 to 423,000 tons a year or 4.2 pounds of paper per household weekly. When the city suspended plastic and glass recycling in 2002, a public outcry persuaded Mayor Michael Bloomberg to retain paper recycling. Half of the mixed paper collected by the Department of Sanitation goes to a number of private companies for processing. The rest goes to the Visy Paper Mill on Staten Island, where it is turned into linerboard for corrugated cardboard.</p>\r\n\r\n<p>We''ve added 1 million tons of paper to your unsorted garbage.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(323, 1, 'n', 'Screen: paper followup sorted', '<p>The U.S. Postal Service processes 80 billion pieces of junk mail annually. In New York City, only 45 percent of paper  is recycled, totaling an estimated 366,000 to 423,000 tons a year or 4.2 pounds of paper per household weekly. When the city suspended plastic and glass recycling in 2002, a public outcry persuaded Mayor Michael Bloomberg to retain paper recycling. Half of the mixed paper collected by the Department of Sanitation goes to a number of private companies for processing. The rest goes to the Visy Paper Mill on Staten Island, where it is turned into linerboard for corrugated cardboard.</p>\r\n\r\n<p>We''ve added 1 million tons of paper to your sorted recycling.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(330, 1, 'n', 'Screen: Ewaste', '<p>When you switched to a new cell phone provider, you got a bonus: the latest, high-tech cell phone, complete with fancy ring tones. What do you do with your old one?</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(380, 1, 'n', 'Screen: ewaste followup landfill', '<p>While the city doesn''t have its own electronics recycling legislation, the Department of Sanitation organizes drop off events, where residents can leave their computers, cell phones, televisions and other electronic devices. More than 8,000 New Yorkers brought 311 tons of  electronics and 2,300 pounds of cell phones to 14 recycling events in fiscal year 2006. E-waste makes up about 2 percent of all of the city''s residential waste (cell phones comprise only .005 percent), but it contains some of the most potentially hazardous toxins. Even so, less than 10 percent of the city''s e-waste is recycled, according to one estimate. The City Council is considering e-waste legislation that would require manufacturers of many types of electronics, from computers to televisions, to recycle the electronics they produce.</p>\r\n\r\n<p>We''ve added 158 tons to your unsorted garbage.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 14:20:19'),
(381, 1, 'n', 'Screen: ewaste followup divert2', '<p>While the city doesn''t have its own electronics recycling legislation, the Department of Sanitation organizes drop off events, where residents can leave their computers, cell phones, televisions and other electronic devices. More than 8,000 New Yorkers brought 311 tons of  electronics and 2,300 pounds of cell phones to 14 recycling events in fiscal year 2006.E-waste makes up about 2 percent of all of the city''s residential waste (cell phones comprise only .005 percent), but it contains some of the most potentially hazardous toxins. Even so, less than 10 percent of the city''s e-waste is recycled, according to one estimate. The City Council is considering e-waste legislation that would require manufacturers of many types of electronics, from computers to televisions, to recycle the electronics they produce.</p>\r\n\r\n<p>The ultimate fate of your phone depends on the contractor running the drop site for the Department of Sanitation. Since only some of the parts they collect can be reused or recycled, we''ve credited you with taking 79 tons out of the waste stream (the cityÃ¢â‚¬â„¢s total amount of sorted and unsorted residential trash) and put 79 tons in your unsorted garbage pile.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(382, 1, 'n', 'Screen: ewaste followup reuse', '<p>While the city doesn''t have its own electronics recycling legislation, the Department of Sanitation organizes drop off events, where residents can leave their old electronic devices. More than 8,000 New Yorkers brought 311 tons of  electronics and 2,300 pounds of cell phones to 14 recycling events in fiscal year 2006. E-waste makes up about 2 percent of all of the city''s residential waste (cell phones comprise only .005 percent), but it contains potentially hazardous toxins. Less than 10 percent of the city''s e-waste is recycled, according to one estimate.</p>\r\n\r\n<p>New Yorkers throw away 158 tons of cell phones a year. By giving your phone to charity, you''ve extended its life. We''ve added 79 tons to your unsorted garbage and credited you with taking 79 tons out of the waste stream (the city''s total amount of sorted and unsorted residential trash).', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(383, 1, 'n', 'Screen: ewaste followup divert', '<p>Who knows what your provider will do with it? But we do know it won''t land in Sanitation Department trucks, which only collect residential waste. We''ve given you credit for diverting 158 tons of garbage from the city. While New York City doesn''t have electronics recycling legislation, state law requires cell phone providers to accept dead phones for recycling and to process those phones on their own dime.</p>\r\n\r\n<p>The Department of Sanitation organizes drop off events to keep additional e-waste out of the landfill. More than 8,000 New Yorkers brought 311 tons of electronics and 2,300 pounds of cell phones to 14 recycling events in fiscal year 2006. E-waste makes up about 2 percent of the city''s residential waste (cell phones comprise only .005 percent), but it contains potentially hazardous toxins. Less than 10 percent of the city''s e-waste is recycled, according to one\r\nestimate. </p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(390, 1, 'y', 'Screen: Settle the Score', '<p>You have had to figure out how to deal with more than 7.6 million tons of waste. If all New Yorkers were just like you, we could divert {tonnage_removed_from_stream} tons of that from the waste stream entirely, so the city would not have to dispose of it at all. You have sorted and set aside {tonnage_sorted} tons for recycling and have another {tonnage_unsorted} ready to be bagged in black. Before we move on, do you want to change your mind about any of your choices so far?<p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 14:20:19'),
(400, 2, 'n', 'Screen: Moving on', '<p>Now it is time for you to play sanitation commissioner! </p>\r\n\r\n<p>All the waste you haven''t diverted from both the unsorted garbage and the city''s recycling program is now ready for curbside pickup. How would you manage all this waste?</p>', 'bg_brownstone_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(410, 2, 'n', 'Screen: sorted/curbside 1', '<p>We''ll start with those sorted recyclables on your curb. Where would you like to direct the Department of Sanitation truck loaded with all that recycling?</p>', 'bg_brownstone_recycle_2.jpg', 0, 0, '2007-11-14 12:34:25'),
(450, 2, 'n', 'screen: Followup: sorted/curbside 1 (local)', '<p>As part of the Bloomberg administration''s Solid Waste Management Plan, each borough is responsible for its share of the city''s waste, or, in this case, the city''s recyclables. You have chosen to send your recyclables to a local station. Currently, most boroughs could accommodate your request -- except for Manhattan. Several state legislators are blocking a measure that would make way for a Manhattan recycling facility on the Gansevoort peninsula near 14th Street. The Assembly members contend the facility would take away from valuable park space. </p>', 'bg_brownstone_recycle_2.jpg', 0, 0, '2007-11-15 17:43:05'),
(455, 2, 'n', 'screen: Followup: sorted/curbside 2 (to NJ)', '<p>With the recycling acceptance facility on the Gansevoort peninsula near 14th Street still awaiting approval, Manhattan''s recyclables are trucked across the Hudson River to Jersey City. Several Manhattan-based Assembly members are blocking the Gansevoort facility, contending the center would take away valuable space in Hudson River Park. Some environmental advocates, however, say the legislators are suffering from a case of NIMBYism.</p>', 'bg_brownstone_recycle_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(457, 2, 'n', 'screen: Followup: sorted/curbside 2 (to outer boro)', '<p>The city''s recyclables go to residential neighborhoods in poor and minority neighborhoods in the outer boroughs. Community activists and environmentalists say the diesel spewing garbage trucks pollute these areas, adding to high asthma rates. Manhattan, on the other hand, has not had to deal with its waste Ã‚Â­ until now. The recycling center slated for Gansevoort peninsula was supposed to change that. But several State Assembly members have blocked the facility, claiming it would intrude on valuable parkland.</p>', 'bg_brownstone_recycle_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(460, 2, 'n', 'Screen:  Sorted Local', '<p>If you live in Manhattan, your recyclables are tipped at the Gansevoort peninsula acceptance facility near 14th Street. If you reside in one of the other boroughs, they''ll arrive at one of several private facilities elsewhere in your borough. Now what?</p>', 'bg_brownstone_recycle_2.jpg', 0, 0, '2007-11-14 12:34:25'),
(500, 2, 'n', 'Screen:  Follow up sorted regional', '<p>At a processing center, recyclables are separated into marketable, sellable raw material. A magnet swoops up your tuna can so it joins other aluminum collected in the city. Though the process is the same no matter where it is done, the location of the facilities and how the materials will be delivered to them have been points of contention. For its part, the Bloomberg administration wants to reduce the number of miles that garbage trucks travel on city streets and through neighborhoods. The administration''s plan for a central facility in Sunset Park replaces many small private contractors with one company -- the Sims Group.</p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(501, 2, 'n', 'Screen:  Follow up sorted Local', '<p>At the citywide center, recyclables are separated into marketable, sellable raw material. A magnet swoops up your tuna can so it joins other aluminum collected in the city. Though the process is the same no matter where it is done, the location of the facilities and how the materials will be delivered to them have been points of contention. For its part, the Bloomberg administration wants to reduce the number of miles that garbage trucks travel on city streets and through neighborhoods. The administration''s plan for a central facility in Sunset Park replaces many small private contractors with one company -- the Sims Group.</p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(510, 2, 'n', 'Screen:  Out of City', '<p>The recyclables made it across the Hudson and are now being sorted into like raw materials. Once they have been processed, where should they go?</p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:34:25'),
(515, 2, 'n', 'Screen:  In City', '<p>After processing, your recyclables are now ready to be sold to a manufacturer and eventually rejoin the market. Where do you think they should go?</p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:34:25'),
(550, 2, 'n', 'Screen:  Follow up out of city local', '<p>Sims, which handles the majority of the city''s recyclable waste, deals secondhand materials all over the world. The appetite for U.S. recycled paper products has grown tremendously, especially in China. But the secondhand market can be extremely competitive. Materials from commercial businesses are worth more than residential waste because they are more homogeneous. While there is an environmental cost for shipping recycled materials overseas, it can be a challenge for raw material processors to sell their products here - partly because of the high cost of doing business in New York City. </p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(560, 2, 'n', 'Screen: Outer Boro', '<p>Welcome to the recycling acceptance facility in Greenpoint. The sanitation truck has tipped and your recyclables will be consolidated with thousands of other plastic bottles and soup cans. Now what?</p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:34:25'),
(600, 2, 'n', 'Screen:  Follow up outer boro', '<p>At the citywide center, recyclables are separated into marketable, sellable raw material. A magnet swoops up your tuna can  so it joins other aluminum collected in the city. Though the process is the same no matter where it is done, the location of the facilities and how the materials will be delivered to them have been points of contention. For its part, the Bloomberg administration wants to reduce the number of miles that garbage trucks travel on city streets and through neighborhoods. The administration''s plan for a central facility in Sunset Park replaces many small private contractors with one company Ã¢â‚¬â€œ the Sims Group.</p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(610, 2, 'n', 'Screen:  Sorted3', '<p>After processing, your recyclables are now ready to be sold to a manufacturer and eventually rejoin the market. Where do you think they should go?</p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:34:25'),
(660, 2, 'n', 'Screen: Follow up', '<p>Sims, which handles the majority of the city''s recyclable waste, deals secondhand materials all over the world. The appetite for U.S. recycled paper products has grown tremendously, especially in China. But the secondhand market can be extremely competitive. Materials from commercial businesses are worth more than residential waste because they are more homogeneous. While there is an environmental cost for shipping recycled materials overseas, it can be a challenge for raw material processors to sell their products here - partly because of the high cost of doing business in New York City.</p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(670, 2, 'n', 'Screen: Unsorted Trash 1', '<p>You''re in the home stretch now! Before you can hang up your Sanitation Commissioner hat, you have just a few more decisions to make, this time about all that unsorted garbage bagged on New York City curbs.</p>\r\n\r\n<p>As your garbage, along with the thousands of tons thrown out across the city, embarks on its journey to its ultimate destination, where should it go first?</p>', 'bg_brownstone_garbage_2.jpg', 0, 0, '2007-11-14 12:34:25'),
(710, 2, 'n', 'Screen: Unsorted Followup', '<p>Since the closing of Fresh Kills in 2001, the city has grappled with what to do with the millions of pounds of garbage that are lofted in black bags onto the city''s streets every day. For years, the City Council and the Bloomberg administration dueled over the problem. Finally, in 2006 the council approved a Solid Waste Management Plan that redirects the city''s waste to local transfer stations, while relying on railcars or barges to transport it to landfills outside the city. This, officials contend, reduces pollution from diesel-spewing trucks, which have carried garbage to New Jersey or the outer boroughs.</p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(720, 2, 'n', 'Screen: Transfer Station', '<P>From the transfer station, where do you want the waste to head?</p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(770, 2, 'n', 'Screen: Transfer Station Followup', '<p>No garbage plan will satisfy all New Yorkers. As the city exports most of its garbage to out of state landfills, it can expect to pay more for dwindling space hundreds of miles away. If it were to use a materials recovery process, some claim it would capture more materials for recycling, but the facility would be costly. An incinerator gets rid of the garbage but can produce pollution and sour stenches. Many remain wary of the environmental impacts of waste to energy plants. And few people want any kind of garbage facility near their home.</p>', 'bg_industrial_2.jpg', 0, 0, '2007-11-14 12:31:15'),
(780, 1, 'n', 'screen: Conclusion box 1', '<p>If the city adopted your approach to handling the the six types of waste we played with in the Garbage Game, here is how your waste management plan would stack up:</p>\r\n<p style="color:#dd3333;">\r\n&#8226; Sanitation trucks will travel {truck_dos_travel} miles within New York City <br />\r\n&#8226; Barges will venture {barge_travel} miles<br />\r\n&#8226; Trucks outside of the city will go {truck_big_travel} miles<br />\r\n&#8226; Rail will travel {rail_travel} miles<br />\r\n&#8226; Total miles: {big_total_mileage}<br/><br/>\r\n\r\nTotal cost: ${total_cost}<br />\r\nTotal volume: {total_tonnage} tons<br />\r\nTotal CO<sub>2</sub> emissions: {total_co2} pounds</p>\r\n<p>Of course we only addressed a fraction of the 64,000 tons of garbage that the Department of Sanitation will contend with this week alone.</p>', 'bg_6.jpg', 0, 0, '2007-11-14 12:31:15'),
(790, 1, 'n', '', '<p>{banner_text}\r\nLet everyone know that you played Gottam Gazette''s Garbage Game. Paste this html on your blog or Web site and take the opportunity to write about the garbage glut and New York''s waste management policies.</p>\r\n\r\n{banner_code}\r\n<p>To have us relay your answers to Mayor Bloomberg and for more information on key city issues, go to the next page.<p>', 'bg_7.jpg', 0, 0, '2007-11-14 12:31:15'),
(810, 1, 'n', '', '<p>Thanks for playing the Gotham Gazette Garbage Game.</p>\r\n<p>To learn more about garbage in New York City, read <a href="http://www.gothamgazette.com/article/issueoftheweek/20071113/200/2343">The Garbage Glut</a>. And for sharp, informative news, analysis and reporting on New York City policy and politics, read <a href="http://www.gothamgazette.com">Gotham Gazette</a>.</p>', 'bg_8.jpg', 0, 0, '2007-11-14 12:31:15'),
(9030, 1, 'n', 'Screen: Plastic', '<p>You''ve quenched your thirst, but you are left with an empty plastic bottle. Select the button below that best reflects what you would do with the empty plastic water bottles.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9060, 1, 'n', 'Screen: Plastic Loopback', '<p>Eventually that bottle will be too bruised to reuse. When that time comes, where will you put it?</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9090, 1, 'n', 'Screen: Plastic Followup - reduce', '<p>You are off to a good start, your waste volume is still zero.</p>\r\n<p>Every New York City household recycles about 2.9 pounds of plastics, metals and glass per week. About half of the plastics collected from the city for recycling are made up of recyclable polyethylene terephthalate, which is what water and soda bottles are made from.  But forget about the bottles. Some New York City officials want residents to give up their Dasani entirely and drink from the faucet.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9095, 1, 'n', 'Screen: Plastic Followup - reuse-trash', '<p>We figure that a bottle will get refilled about three times on average, so we''ve reduced the volume of water bottle waste in your unsorted waste stream to 25 percent of the 17,677 tons that New Yorkers currently generate each year, or 4,420 tons.</p>\r\n<p>Every New York City household recycles about 2.9 pounds of plastics, metals and glass per week. About half of the plastics collected from the city for recycling are made up of recyclable polyethylene terephthalate, which is what water and soda bottles are made from. But forget about the bottles. Some New York City officials want residents to give up their Dasani entirely and drink from the faucet.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9096, 1, 'n', 'Screen: Plastic Followup - reuse-recycle', '<p>We figure that a bottle will get refilled about three times on average, so we''ve reduced the volume of water bottle waste in your sorted recycling to 25 percent of the 17,677 tons that New Yorkers currently generate each year, or 4,420 tons.</p>\r\n<p>Every New York City household recycles about 2.9 pounds of plastics, metals and glass per week. About half of the plastics collected from the city for recycling are made up of recyclable polyethylene terephthalate, which is what water and soda bottles are made from. But forget about the bottles. Some New York City officials want residents to give up their Dasani entirely and drink from the faucet.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9097, 1, 'n', 'Screen: Plastic Followup - recycle', '<p><b>17,677</b> tons of plastic bottles will land at the curb this year if New Yorkers keep up their disposable bottle habit. We''ve added <b>17,677</b> of water bottles to your sorted recycling pile.</p>\r\n<p>Every New York City household recycles about 2.9 pounds of plastics, metals and glass per week. About half of the plastics collected from the city for recycling are made up of recyclable polyethylene terephthalate, which is what water and soda bottles are made from. But forget about the bottles. Some New York City officials want residents to give up their Dasani entirely and drink from the faucet.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9099, 1, 'n', 'Screen: Plastic Followup - trash', '<p><b>17,677</b> tons of plastic bottles will land at the curb this year if New Yorkers keep up their disposable bottle habit. We''ve added <b>17,677</b> to your trash pile.</p>\r\n<p>Every New York City household recycles about 2.9 pounds of plastics, metals and glass per week. About half of the plastics collected from the city for recycling are made up of recyclable polyethylene terephthalate, which is what water and soda bottles are made from.  But forget about the bottles. Some New York City officials want residents to give up their Dasani entirely and drink from the faucet.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9100, 1, 'n', 'Screen: Towel', '<p>Your fraying bathroom towels are starting to wear you out, and the new ones you''ve bought go better with your d&eacute;cor anyway. What will you do with your old towel?</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9140, 1, 'n', 'Screen: Towel Followup - reuse', '<p>Clothing and textiles make up 5.7 percent of New York City''s garbage. New York City currently does not recycle or compost this material, although a garbage plan approved by City Council in 1992 called for recycling cloth. Beyond keeping your towel out of the waste stream for a while, using worn-out cloth for household chores reduces your use of paper towels and other disposable products. More than 90 percent of U.S. homes use paper towels, producing 3,000 tons of waste a day and destroying vast tracts of forest.</p>\r\n<p> We''ve added 9,278 tons to your waste stream, a credit of 50 percent for ensuring that your towel will continue to be used.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9145, 1, 'n', 'Screen: Towel Followup - trash', '<p>Clothing and textiles make up 5.7 percent of New York City''s garbage. New York City currently does not recycle or compost this material, although a garbage plan approved by City Council in 1992 called for recycling cloth. Beyond keeping your towel out of the waste stream for a while, using worn-out cloth for household chores reduces your use of paper towels and other disposable products. More than 90 percent of U.S. homes use paper towels, producing 3,000 tons of waste a day and destroying vast tracts of forest.</p>\r\n\r\n<p>We''ve added 18,556 to your waste stream.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9150, 1, 'n', 'screen: Compost', 'The farmer''s market had a bumper crop of apples this week. Now that you''ve munched your Honeycrisps down to the core, what will you do with what''s left?', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9190, 1, 'n', 'screen: Compost followup', '<p>Composting is the controlled decomposition of organic material so that it becomes soil. The city collects and composts leaves and some yard waste and runs a composting operation for food waste on Riker''s Island. Some community gardens compost food waste. In the late 1990s, the city conducted a pilot program for backyard composting and concluded a citywide program would divert less than 1 percent  of the waste stream. But some cities have done more. In Toronto, residents sort out compostable materials. The city collects and processes the waste, producing soil for farms and  parks. Officials hope the program will reduce the  garbage headed to landfills by about 30 percent.</p>\r\n\r\n<p>New York City households throw away about 745,000 tons of food waste each year. We''ve added that volume to your waste stream.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9191, 1, 'n', 'screen: Compost followup divert', '<p>Composting is the controlled decomposition of organic material so that it becomes soil. The city collects and composts leaves and some yard waste and runs a composting operation for food waste on Riker''s Island. Some community gardens compost food waste. In the late 1990s, the city conducted a pilot program for backyard composting and concluded a citywide program would divert less than 1 percent  of the waste stream. But some cities have done more. In Toronto, residents sort out compostable materials. The city collects and processes the waste, producing soil for farms and  parks. Officials hope the program will reduce the  garbage headed to landfills by about 30 percent.</p>\r\n\r\n<p>We''ve added 745,000 tons of sloppy food scraps to the waste you''ve diverted from the municipal waste stream.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9192, 1, 'n', 'screen: Compost followup sort', '<p>Composting is the controlled decomposition of organic material so that it becomes soil. The city collects and composts leaves and some yard waste and runs a composting operation for food waste on Riker''s Island. Some community gardens compost food waste. In the late 1990s, the city conducted a pilot program for backyard composting and concluded a citywide program would divert less than 1 percent  of the waste stream. But some cities have done more. In Toronto, residents sort out compostable materials. The city collects and processes the waste, producing soil for farms and  parks. Officials hope the program will reduce the  garbage headed to landfills by about 30 percent.</p>\r\n<p>New York City households throw away about 745,000 tons of food waste each year. We''ve added that volume to your sorted recycling.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9200, 1, 'n', 'screen: Diaper', '<p>Your baby woke up wailing with a dirty diaper. She''s sleeping soundly again, but you''re left holding a soiled Pamper.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9230, 1, 'n', 'Screen: Hard to Divert', '<p>We know you are just kidding about that. Seriously, how should we handle hard to divert waste like stinky diapers and old tennis balls?</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9240, 1, 'n', 'Screen: Hard to Divert', '<p>Some disposable diapers can be composted, but New York City doesn''t have any plans in the works to take diapers in a regular compost pickup.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9260, 1, 'n', 'Screen: diaper followup reduce', '<p>If you have a baby, you use diapers. About 90 percent of U.S. families opt for disposables. With the average baby going through about five a day, Americans throw away 3.6 million tons of diapers a year. Alternatives are emerging. Toronto accepts diapers for composting, but the city must separate out the plastic covering and send that to a landfill. Flushable diapers have come on the market. And many environmentally conscious parents opt for cloth. That decision reduces garbage in the landfill. But disposable diapers use 29 percent less energy than cloth diapers washed at home and less water as well.</p>\r\n<p>Since most parents use disposable diapers, New Yorkers throw away 116,480 tons of diapers a year. You''ve kept 100 percent of that out of the waste stream.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9261, 1, 'n', 'Screen: diaper followup unsorted', '<p>If you have a baby, you use diapers. About 90 percent of U.S. families opt for disposables. With the average baby going through about five a day, Americans throw away 3.6 million tons of diapers a year. Alternatives are emerging. Toronto accepts diapers for composting, but the city must separate out the plastic covering and send that to a landfill. Flushable diapers have come on the market. And many environmentally conscious parents opt for cloth. That decision reduces garbage in the landfill. But disposable diapers use 29 percent less energy than cloth diapers washed at home and less water as well.</p>\r\n<p>New Yorkers throw away 116,480 tons of disposable diapers a year. We''ve increased your unsorted garbage by 116,480 tons.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9270, 1, 'n', 'Screen: Paper', '<p>You have received another piece of junk mail. Though the offer is enticing (well, not really), you now have to dispose of the paper. Would you:</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9290, 1, 'n', 'Screen: Paper Loop', '<p>Kudos for reusing it. We''ll reduce your waste stream impact by 50 percent, but now it really is refuse. Will you ...</p>\r\n', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9320, 1, 'n', 'Screen: paper followup reuse unsorted', '60', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9321, 1, 'n', 'Screen: paper followup reuse sorted', '<p>The U.S. Postal Service processes 80 billion pieces of junk mail annually. In New York City, only 45 percent of paper  is recycled, totaling an estimated 366,000 to 423,000 tons a year or 4.2 pounds of paper per household weekly. When the city suspended plastic and glass recycling in 2002, a public outcry persuaded Mayor Michael Bloomberg to retain paper recycling. Half of the mixed paper collected by the Department of Sanitation goes to a number of private companies for processing. The rest goes to the Visy Paper Mill on Staten Island, where it is turned into linerboard for corrugated cardboard.</p>\r\n<p>We''ve added 500,000 tons of paper to your sorted recycling.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9322, 1, 'n', 'Screen: paper followup unsorted', '<p>The U.S. Postal Service processes 80 billion pieces of junk mail annually. In New York City, only 45 percent of paper  is recycled, totaling an estimated 366,000 to 423,000 tons a year or 4.2 pounds of paper per household weekly. When the city suspended plastic and glass recycling in 2002, a public outcry persuaded Mayor Michael Bloomberg to retain paper recycling. Half of the mixed paper collected by the Department of Sanitation goes to a number of private companies for processing. The rest goes to the Visy Paper Mill on Staten Island, where it is turned into linerboard for corrugated cardboard.</p>\r\n<p>We''ve added 1 million tons of paper to your unsorted garbage.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9323, 1, 'n', 'Screen: paper followup sorted', '<p>The U.S. Postal Service processes 80 billion pieces of junk mail annually. In New York City, only 45 percent of paper  is recycled, totaling an estimated 366,000 to 423,000 tons a year or 4.2 pounds of paper per household weekly. When the city suspended plastic and glass recycling in 2002, a public outcry persuaded Mayor Michael Bloomberg to retain paper recycling. Half of the mixed paper collected by the Department of Sanitation goes to a number of private companies for processing. The rest goes to the Visy Paper Mill on Staten Island, where it is turned into linerboard for corrugated cardboard.</p>\r\n<p>We''ve added 1 million tons of paper to your sorted recycling.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9330, 1, 'n', 'Screen: Ewaste', '<p>When you switched to a new cell phone provider, you got a bonus: the latest, high-tech cell phone, complete with fancy ring tones. What do you do with your old one?</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9380, 1, 'n', 'Screen: ewaste followup landfill', '<p>While the city doesn''t have its own electronics recycling legislation, the Department of Sanitation organizes drop off events, where residents can leave their computers, cell phones, televisions and other electronic devices. More than 8,000 New Yorkers brought 311 tons of  electronics and 2,300 pounds of cell phones to 14 recycling events in fiscal year 2006. E-waste makes up about 2 percent of the city''s waste stream (cell phones comprise only .005 percent), but it contains some of the most potentially hazardous toxins. Even so, less than 10 percent of the city''s e-waste is recycled, according to one estimate. The City Council is considering e-waste legislation that would require manufacturers of many types of electronics, from computers to televisions, to recycle the electronics they produce.</p>\r\n\r\n<p>We''ve added 158 tons to your unsorted garbage.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9381, 1, 'n', 'Screen: ewaste followup divert2', '<p>While the city doesn''t have its own electronics recycling legislation, the Department of Sanitation organizes drop off events, where residents can leave their computers, cell phones, televisions and other electronic devices. More than 8,000 New Yorkers brought 311 tons of  electronics and 2,300 pounds of cell phones to 14 recycling events in fiscal year 2006. E-waste makes up about 2 percent of the city''s waste stream (cell phones comprise only .005 percent), but it contains some of the most potentially hazardous toxins. Even so, less than 10 percent of the city''s e-waste is recycled, according to one estimate. The City Council is considering e-waste legislation that would require manufacturers of many types of electronics, from computers to televisions, to recycle the electronics they produce.</p>\r\n<p>The ultimate fate of your phone depends on the contractor running the drop site for the Department of Sanitation. Since only some of the parts they collect can be reused or recycled, we''ve given you 79 tons of waste stream diversion and put 79 tons in your unsorted garbage pile.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15');
INSERT INTO `text_input` (`rec_order`, `layout_template`, `change_choices`, `short_text`, `text_content`, `bg_image`, `bg_pos_x`, `bg_pos_y`, `timestamp`) VALUES
(9382, 1, 'n', 'Screen: ewaste followup reuse', '<p>While the city doesn''t have its own electronics recycling legislation, the Department of Sanitation organizes drop off events, where residents can leave their computers, cell phones, televisions and other electronic devices. More than 8,000 New Yorkers brought 311 tons of  electronics and 2,300 pounds of cell phones to 14 recycling events in fiscal year 2006. E-waste makes up about 2 percent of the city''s waste stream (cell phones comprise only .005 percent), but it contains some of the most potentially hazardous toxins. Even so, less than 10 percent of the city''s e-waste is recycled, according to one estimate. The City Council is considering e-waste legislation that would require manufacturers of many types of electronics, from computers to televisions, to recycle the electronics they produce.</p>\r\n\r\n<p>New Yorkers throw away 158 tons of cell phones a year. By giving your phone to charity, you''ve extended its life. We''ve added 79 tons to your unsorted garbage and credited you with 79 tons \r\n of waste stream diversion.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15'),
(9383, 1, 'n', 'Screen: ewaste followup divert', '<p>While the city doesn''t have its own electronics recycling legislation, the Department of Sanitation organizes drop off events, where residents can leave their computers, cell phones, televisions and other electronic devices. More than 8,000 New Yorkers brought 311 tons of  electronics and 2,300 pounds of cell phones to 14 recycling events in fiscal year 2006. E-waste makes up about 2 percent of the city''s waste stream (cell phones comprise only .005 percent), but it contains some of the most potentially hazardous toxins. Even so, less than 10 percent of the city''s e-waste is recycled, according to one estimate. The City Council is considering e-waste legislation that would require manufacturers of many types of electronics, from computers to televisions, to recycle the electronics they produce.</p>\r\n\r\n<p>Who knows what your provider will do with it? All we know for sure is\r\nthat it won''t land in Sanitation Department trucks, which only collect\r\nresidential waste. We''ve given you credit for diverting 158 tons of\r\ngarbage from the municipal waste stream.</p>', 'bg_kitchen.jpg', 0, 0, '2007-11-14 12:31:15');


--
-- Table structure for table `users`
--
CREATE TABLE IF NOT EXISTS `users` (
  `rec_id` int(11) NOT NULL auto_increment,
  `session_id` varchar(50) NOT NULL default '',
  `first` varchar(40) default NULL,
  `last` varchar(40) default NULL,
  `email` varchar(40) default NULL,
  `address_1` varchar(100) default NULL,
  `address_2` varchar(100) default NULL,
  `city` varchar(100) default NULL,
  `state` char(2) default NULL,
  `zip` int(9) default NULL,
  `custom_07_write_mayor` enum('yes','no') default NULL,
  `07_garbage_game_comments` mediumtext,
  `format` enum('plain','mime') default NULL,
  `slid_1` varchar(70) default NULL,
  `slid_2` varchar(70) default NULL,
  `slid_3` varchar(70) default NULL,
  `banner_image` varchar(25) default NULL,
  `ip_add` varchar(20) default NULL,
  `timestamp` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`rec_id`),
  KEY `zip` (`zip`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COMMENT='Record of users who complete the game' AUTO_INCREMENT=11562 ;


--
-- Table structure for table `user_choices`
--

CREATE TABLE IF NOT EXISTS `user_choices` (
  `session_id` varchar(30) NOT NULL default '',
  `array_name` varchar(40) NOT NULL default '',
  `button_number` int(11) NOT NULL default '0',
  `value` varchar(50) NOT NULL default '',
  `timestamp` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  KEY `session_id` (`session_id`),
  KEY `array_name` (`array_name`),
  KEY `button_number` (`button_number`),
  KEY `value` (`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
